Importing Libraries

In [10]:
import zipfile
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from sklearn.metrics import confusion_matrix, accuracy_score
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense,Dropout,BatchNormalization

Importing and loading Dataset 

In [2]:
fine_labels = pd.read_csv("fine_labels.csv")
train_Image = np.load('trnImage.npy')
test_Image = np.load('tstImage.npy')
train_Label = np.load('trnLabel_fine.npy')
test_Label = np.load('tstLabel_fine.npy')

train_Image=train_Image.transpose((3,0,1,2))
test_Image=test_Image.transpose((3,0,1,2))

Preprocess and reshaping data

In [3]:
print("Train Image:",train_Image.shape)
print("Train Label:",train_Label.shape)

print("Test Image:",test_Image.shape)
print("Test Label:",test_Label.shape)

Train Image: (50000, 32, 32, 3)
Train Label: (50000,)
Test Image: (10000, 32, 32, 3)
Test Label: (10000,)


Building CNN

In [16]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.5))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.5))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.5))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Flatten())

model.add(Dense(100, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(train_Image, train_Label, batch_size=512,steps_per_epoch=len(train_Image) / 512,validation_data=(test_Image, test_Label),epochs=100,verbose=1)

Epoch 1/100
97/97 [==============================] - 27s 244ms/step - loss: 4.5665 - accuracy: 0.0142 - val_loss: 4.4697 - val_accuracy: 0.0242
Epoch 2/100
97/97 [==============================] - 19s 198ms/step - loss: 4.3437 - accuracy: 0.0294 - val_loss: 4.2883 - val_accuracy: 0.0577
Epoch 3/100
97/97 [==============================] - 18s 187ms/step - loss: 4.1495 - accuracy: 0.0585 - val_loss: 4.1281 - val_accuracy: 0.0727
Epoch 4/100
97/97 [==============================] - 18s 185ms/step - loss: 3.9524 - accuracy: 0.0864 - val_loss: 3.9279 - val_accuracy: 0.1149
Epoch 5/100
97/97 [==============================] - 18s 188ms/step - loss: 3.8174 - accuracy: 0.1074 - val_loss: 3.7643 - val_accuracy: 0.1394
Epoch 6/100
97/97 [==============================] - 18s 181ms/step - loss: 3.7226 - accuracy: 0.1235 - val_loss: 3.6682 - val_accuracy: 0.1498
Epoch 7/100
97/97 [==============================] - 18s 188ms/step - loss: 3.6583 - accuracy: 0.1336 - val_loss: 3.6130 - val_accuracy:

Evaluating Model

In [17]:
predictions = model.predict(test_Image)
predicted_labels = np.argmax(predictions, axis=1)
true_labels = test_Label

313/313 [==============================] - 3s 7ms/step


Confusion Matrix

In [18]:
# Confusion Matrix
conf_matrix = confusion_matrix(true_labels, predicted_labels)
print("Confusion Matrix:\n", conf_matrix)

Confusion Matrix:
 [[69  3  0 ...  0  0  0]
 [ 0 46  0 ...  1  0  0]
 [ 1  0 27 ...  2  0  0]
 ...
 [ 0  0  0 ... 29  0  0]
 [ 0  1  8 ...  1  9  1]
 [ 0  1  1 ...  0  0 17]]


Data accuracy

In [19]:
accuracy = accuracy_score(test_Label, predicted_labels)
print("Accuracy:", accuracy*100,"%")

Accuracy: 33.31 %
